package codexruntime

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func privateSkillRoot(t *testing.T) string {
	t.Helper()
	root := filepath.Join(t.TempDir(), "skills")
	if err := os.Mkdir(root, 0o700); err != nil {
		t.Fatal(err)
	}
	return root
}

// testdata/published-receipts/<tag>/{codex,claude}.receipt are the exact
// skill-set receipts each published stable release wrote through `axiom
// first-run` (Claude receipts with their skill root replaced by {{ROOT}}).
// They were captured from the released macOS arm64 binaries, not generated by
// this code, so they detect a receipt serialization that drifts from what an
// earlier release really wrote (issue #186: a five-skill receipt was
// re-derived with the current six skill names and never recognized again).
// Add the new release's receipts here whenever a stable release is published.
func publishedReceiptTags(t *testing.T) []string {
	t.Helper()
	entries, err := os.ReadDir(filepath.Join("testdata", "published-receipts"))
	if err != nil {
		t.Fatal(err)
	}
	tags := []string{}
	for _, entry := range entries {
		if entry.IsDir() {
			tags = append(tags, entry.Name())
		}
	}
	if len(tags) == 0 {
		t.Fatal("no published receipt fixtures")
	}
	return tags
}

func publishedReceipt(t *testing.T, tag, runtime, root string) []byte {
	t.Helper()
	wire, err := os.ReadFile(filepath.Join("testdata", "published-receipts", tag, runtime+".receipt"))
	if err != nil {
		t.Fatal(err)
	}
	return []byte(strings.ReplaceAll(string(wire), "{{ROOT}}", root))
}

func TestEveryPublishedReceiptIsRecognizedAsAxiomOwned(t *testing.T) {
	for _, tag := range publishedReceiptTags(t) {
		for _, runtime := range []string{"codex", "claude"} {
			t.Run(tag+"/"+runtime, func(t *testing.T) {
				root := privateSkillRoot(t)
				service, err := New(root)
				if runtime == "claude" {
					service, err = NewClaude(root)
				}
				if err != nil {
					t.Fatal(err)
				}
				wire := publishedReceipt(t, tag, runtime, root)
				if err := os.WriteFile(filepath.Join(root, receiptName), wire, 0o600); err != nil {
					t.Fatal(err)
				}
				current, err := service.integration.receipt(root)
				if err != nil {
					t.Fatal(err)
				}
				if string(current) != string(wire) && !service.integration.matchesLegacyReceipt(root) {
					t.Fatalf("receipt written by %s is not recognized as Axiom-owned:\n%s", tag, wire)
				}
				inventory, err := service.Inventory(context.Background())
				if err != nil {
					t.Fatal(err)
				}
				if inventory.Receipt == "foreign" {
					t.Fatalf("receipt written by %s classified foreign", tag)
				}
			})
		}
	}
}

// Every skill digest a published release recorded in its Claude receipt is a
// known Axiom revision, so the skill it describes is owned_older, never a
// conflict.
func TestEveryPublishedSkillDigestIsKnown(t *testing.T) {
	current, err := currentRevision()
	if err != nil {
		t.Fatal(err)
	}
	for _, tag := range publishedReceiptTags(t) {
		for _, line := range strings.Split(string(publishedReceipt(t, tag, "claude", "/r")), "\n") {
			key, digest, ok := strings.Cut(line, "=")
			name, skill := strings.CutPrefix(key, "skill.")
			if !ok || !skill {
				continue
			}
			if current.skills[name] != digest && !claudeIntegration.knownDigest(name, digest) {
				t.Fatalf("%s published %s=%s, which is neither embedded nor in sharedSkillHistory", tag, name, digest)
			}
		}
	}
}

// A Runtime root that a published release configured converges with this
// binary: every skill is replaced or created and the receipt becomes current.
func TestEveryPublishedClaudeInstallationConverges(t *testing.T) {
	for _, tag := range publishedReceiptTags(t) {
		t.Run(tag, func(t *testing.T) {
			root := privateSkillRoot(t)
			service, err := NewClaude(root)
			if err != nil {
				t.Fatal(err)
			}
			wire := publishedReceipt(t, tag, "claude", root)
			for _, line := range strings.Split(string(wire), "\n") {
				key, digest, ok := strings.Cut(line, "=")
				name, skill := strings.CutPrefix(key, "skill.")
				if !ok || !skill {
					continue
				}
				content := historicalSkillContent(t, name, digest)
				if content == nil {
					continue
				}
				writePrivateSkill(t, root, name, content)
			}
			if err := os.WriteFile(filepath.Join(root, receiptName), wire, 0o600); err != nil {
				t.Fatal(err)
			}
			result := service.Install(context.Background())
			if result.Status != Applied && result.Status != Unchanged {
				t.Fatalf("install over %s = %+v", tag, result)
			}
			if again := service.Install(context.Background()); again.Status != Unchanged {
				t.Fatalf("rerun over %s = %+v", tag, again)
			}
			if ready := service.Inspect(context.Background()); ready.Status != Ready {
				t.Fatalf("inspect after %s = %+v", tag, ready)
			}
		})
	}
}

// historicalSkillContent returns content with the given digest when this
// binary embeds it; earlier texts are not kept, so for them the test seeds a
// stand-in only through the ownership history (nil skips the skill, which
// exercises the missing-skill path the five-skill releases produce).
func historicalSkillContent(t *testing.T, name, digest string) []byte {
	t.Helper()
	content, err := skillFiles.(interface {
		ReadFile(string) ([]byte, error)
	}).ReadFile("skills/" + name + "/SKILL.md")
	if err != nil || digestOf(content) != digest {
		return nil
	}
	return content
}

func writePrivateSkill(t *testing.T, root, name string, content []byte) {
	t.Helper()
	directory := filepath.Join(root, name)
	if err := os.Mkdir(directory, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(directory, "SKILL.md"), content, 0o600); err != nil {
		t.Fatal(err)
	}
}

// Issue #186: over a root a five-skill release configured, an edited Axiom
// skill is "modified" (the recognized receipt attests Axiom installed it), an
// unknown skill is "foreign", and a receipt Axiom never wrote is reported as
// its own conflict. Nothing is overwritten and every artifact is named.
func TestConflictsNameTheArtifactAndDistinguishModifiedFromForeign(t *testing.T) {
	root := privateSkillRoot(t)
	service, err := NewClaude(root)
	if err != nil {
		t.Fatal(err)
	}
	writePrivateSkill(t, root, "axiom-work-item-run", []byte("edited by the user\n"))
	writePrivateSkill(t, root, "axiom-project-list", []byte("someone else's skill\n"))
	if err := os.WriteFile(filepath.Join(root, receiptName), publishedReceipt(t, "v0.1.1", "claude", root), 0o600); err != nil {
		t.Fatal(err)
	}
	got := service.Install(context.Background())
	want := []Conflict{
		{Artifact: "axiom-project-list/SKILL.md", State: "foreign", Digest: digestOf([]byte("someone else's skill\n"))},
		{Artifact: "axiom-work-item-run/SKILL.md", State: "modified", Digest: digestOf([]byte("edited by the user\n"))},
	}
	if got.Status != Failed || got.Category != "claude_skill_conflict" || got.Receipt != ReceiptLegacy || len(got.Conflicts) != len(want) || got.Conflicts[0] != want[0] || got.Conflicts[1] != want[1] {
		t.Fatalf("install = %#v", got)
	}
	if content, _ := os.ReadFile(filepath.Join(root, "axiom-work-item-run", "SKILL.md")); string(content) != "edited by the user\n" {
		t.Fatalf("modified skill overwritten: %q", content)
	}

	other := privateSkillRoot(t)
	service, err = NewClaude(other)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(other, receiptName), []byte("not an Axiom receipt\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	writePrivateSkill(t, other, "axiom-work-item-run", historicalSkillContentOrSkip(t, "axiom-work-item-run"))
	got = service.Install(context.Background())
	if got.Status != Failed || got.Receipt != ReceiptUnrecognized || len(got.Conflicts) != 1 || got.Conflicts[0] != (Conflict{Artifact: receiptName, State: "receipt_unrecognized"}) {
		t.Fatalf("unrecognized receipt install = %#v", got)
	}
	if content, _ := os.ReadFile(filepath.Join(other, receiptName)); string(content) != "not an Axiom receipt\n" {
		t.Fatalf("receipt overwritten: %q", content)
	}
}

// historicalSkillContentOrSkip returns an owned_older stand-in for name: the
// test needs a skill that requires replacement, which only an earlier
// revision's exact text provides, so the current text is altered through
// ownership history instead when no earlier text is embedded.
func historicalSkillContentOrSkip(t *testing.T, name string) []byte {
	t.Helper()
	content := []byte("legacy " + name + "\n")
	original := sharedSkillHistory
	t.Cleanup(func() { sharedSkillHistory = original })
	sharedSkillHistory = append(append([]skillSetRevision(nil), original...), skillSetRevision{skillSetVersion: "2", binaryCompatibility: "2", skills: map[string]string{name: digestOf(content)}})
	return content
}
